"""PDF export helpers for generated Markdown notes."""

from __future__ import annotations

import re
from datetime import datetime
from html import escape
from io import BytesIO

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def _format_inline_markdown(text: str) -> str:
    """Escape text for ReportLab and retain simple bold/code Markdown styling."""
    safe_text = escape(text)
    safe_text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", safe_text)
    return re.sub(r"`(.+?)`", r"<font name='Courier'>\1</font>", safe_text)


def _add_page_number(canvas, document) -> None:
    """Put a subtle footer on each PDF page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(HexColor("#6B7280"))
    canvas.drawRightString(A4[0] - 1.8 * cm, 1.2 * cm, f"Page {document.page}")
    canvas.restoreState()


def create_notes_pdf(topic: str, notes: str, timestamp: str) -> bytes:
    """Convert generated Markdown notes into a readable PDF byte string."""
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=1.8 * cm,
        rightMargin=1.8 * cm,
        topMargin=1.8 * cm,
        bottomMargin=1.8 * cm,
        title=f"AI Notes - {topic}",
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "NotesTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=HexColor("#111827"),
        spaceAfter=8,
    )
    meta_style = ParagraphStyle(
        "NotesMeta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=HexColor("#6B7280"),
        spaceAfter=16,
    )
    heading_style = ParagraphStyle(
        "NotesHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=HexColor("#1F2937"),
        spaceBefore=10,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "NotesBody",
        parent=styles["BodyText"],
        fontSize=10.5,
        leading=15,
        spaceAfter=7,
    )

    try:
        saved_at = datetime.fromisoformat(timestamp).strftime("%d %b %Y, %I:%M %p")
    except (TypeError, ValueError):
        saved_at = timestamp

    story = [
        Paragraph(_format_inline_markdown(topic), title_style),
        Paragraph(f"Generated by AI Notes Generator · {_format_inline_markdown(saved_at)}", meta_style),
    ]

    for raw_line in notes.splitlines():
        line = raw_line.strip()
        if not line:
            story.append(Spacer(1, 4))
            continue

        heading_match = re.match(r"^#{1,6}\s+(.+)$", line)
        bullet_match = re.match(r"^(?:[-*+]\s+|\d+[.)]\s+)(.+)$", line)
        if heading_match:
            story.append(Paragraph(_format_inline_markdown(heading_match.group(1)), heading_style))
        elif bullet_match:
            story.append(
                Paragraph(_format_inline_markdown(bullet_match.group(1)), body_style, bulletText="•")
            )
        else:
            story.append(Paragraph(_format_inline_markdown(line), body_style))

    document.build(story, onFirstPage=_add_page_number, onLaterPages=_add_page_number)
    return buffer.getvalue()
